### ISSUE TITLE
Use comments instead

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#21]
@jimhester As it happens  I am not using `argufy` in my own projects, I am not sure why. I am just somehow uncomfortable with it, maybe because I am not happy with the syntax. It seems heavy.

So, how about trying to use comments instead? :) I am serious.

E.g. something like

``` r
prefix <-function(
    str,            #' as.character
    len = 3         #' is.numeric
) {
  substring(x, 1, y)
})
```

Then you could just run `argufy_package` on it.

**Comment by jimhester** [comment]
Only issue with using comments is they are dropped from the `parse()` output unless `options(keep.source)` is `TRUE` (or `keep.source.pkgs = TRUE` if installing a package). So `argufy_package()` would not have the information contained in the comments to argufy with.

**Comment by gaborcsardi** [comment]
Good point. `keep.source.pkgs` is apparently `FALSE` by default.....

It is a pity, because we could just run `argufy_package` as the last thing, after all the functions were created.

**Comment by gaborcsardi** [comment]
Hmmmm. How could we run `argufy_package` on all function, as part of installing a package?

**Comment by gaborcsardi** [comment]
OK, another random idea. Can we write this as a roxygen2 roclet?

I am not quite sure where the generated code would be put, though.....

**Comment by lawremi** [comment]
Since roxygen already documents arguments, why not add a formalism to roxygen for specifying types and assertions on the args?  This will help eliminate redundancy, since often people mention the type in the document string anyway. I could imagine something like:

```
#' @param pos An $integer indicating the position 
```

The downside is that the assertion is not immediately proximate to the code, as it would be in statically typed language, but as you say, it does add clutter. This would also help with #18.

**Comment by gaborcsardi** [comment]
@lawremi Great idea! 

There technicalities to think about:
- would this be part of roxygen, really, or a separate, pre-processing step?
- when should we add the checks/conversions to the functions? When roxygen runs? Or in .onLoad()? 
- if the checks are added by roxygen, where should we put the new, augmented code?

Some relevant discussion from an email exchange with @jimhester 

---

> > However one way we could implement it would be to have roxygen2 read the
> > annotations or type constraints within the argument descriptions (like those
> > in withr
> > https://github.com/jimhester/withr/blob/master/man/with_collate.Rd#L10)
> > generate the appropriate argufy code for each relevant function and store it
> > in R/sysdata.rda.
> > [...]

Another idea on top of this. roxygen2 supports brew templates, and these
can run arbitrary R code. Unfortunately the templates run in an empty
environment, so
we would either need to convince Hadley to pass the parsed docs to
them or we can
also get them from some parent frame for now.

Then you could put the argument specifications within the roxygen
markup, all you
would need is an extra @template argufy tag. E.g.

``` r
#' Title
#'
#' Description
#'
#' @template argufy
#' @param x [character(1)] First argument...
#' @param y [numeric(1)] Second argument...

f <- function(x, y) { ... }
```

Or we can also put the type/conversion information into an Rd comment:

``` r
#' @template argufy
#' @param x % character(1)
#'   First argument...
#' @param y % numeric(1) && y < 10
#'   Second argument...
```

Or we can define a custom Rd command for this:

``` r
#' @template argufy
#' @param x \assert{is.character(x)}
#'   First argument...
#' @param y \assert{is.numeric(x) && y < 10}
#'   Second argument...
```

Although this is getting tedious and then you might as well write
`stopifnot(...)` in the code... anyway, maybe we can come up with some
reasonable syntax that reads well in the docs, and it is easy to parse
it.

**Comment by jimhester** [comment]
One issue with this approach is this limits the type checking to documented functions. Although you can technically document internal functions with roxygen, so it is probably OK in practice.

**Comment by gaborcsardi** [comment]
@jimhester I document internal functions with roxygen quite frequently, actually. Either with `@noRd` or `@keywords internal` is fine I think, depending on your preferences.

Btw. I like the human readable syntax as well, but supporting more complex assertions and conversions might be tricky this way.

**Comment by lawremi** [comment]
It's important not to forget the semantic advantages. Even if the syntax ends up being equivalent to `stopifnot()`, the assertions are formally declared, and there is no need to rely on heuristic static analysis to derive them. 

There needs to be a general and extensible framework for processing R packages. I have discussed this at length with @gmbecker. I'm not that familiar with roxygen, but it might well serve as a prototyping platform for these ideas. Roxygen has worked well so far by treating the .R file as the source for everything. If we want the R code itself to be generated/modified, I can think of two possibilities:
1. Create an entirely separate source document, not necessarily in the `R` directory, and the system generates one or more R files in the `R` directory,
2. Generate the R code at runtime, perhaps based on code-rewriting rules that were generated by roxygen.

I like the second, just because it does not change the location of the source, nor produce a mash-up of hand-written and generated source files. The runtime code patching could be implemented by some package, not necessarily roxygen2, but the generation of the rules would happen through a "roclet". 

I like your syntax:

```
#' @param x [character(1)] First argument...
```

**Comment by gmbecker** [comment]
I've done some similar work in using roxygen-like comments to declare S4 classes and methods. I haven't pushed that work to completion yet, but I think there's a lot of opportunities in these types of approaches. Declaring S3 methods like this would be even more straightforward.

I agree with @lawremi that a general, powerful framework would be beneficial. Imagine a build mechanism which can roxygenize, argufy, and S4ify commented code.

Furthermore, as Michael hints at, if we keep these assertions around and accessible then we have a powerful tool for static analysis and potential compilation of code which uses it. This could open up a lot of really fun doors if it catches on in any meaningful way. 

I think we want both versions of code accessible somehow. Whether that means copying unmodified code into inst/ during the argufy process, or some other way is mostly an implementation detail, I think.

In terms of seperate source documents, R does already support the concept of .Rin files via makefiles, and IIRC they are used in places in R itself, so there is precedent there, though we'd want something nicer than having to write a make file, I think.

I'd love to collaborate with you guys on this. (Was in the process of writing an email to that effect when I got the namecheck notification from github).

**Comment by gaborcsardi** [comment]
I really like the idea of a static analyzer based on argument type declarations in general, but I really doubt that this project will be it. It might be a good step towards such an analyzer, though.

To answer and elaborate some of the other comments:
- It seems like we converge towards using roxygen to parse the assertions, generate the check code and then put it _somewhere_ in the package. Where exactly is tricky, but we can probably work out some not too painful solution.
- I am not sure what you mean by run-time, this is tricky with R packages. Personally, I like install-time best. Load-time is also not too bad, but it probably screws up byte-compiling, and I guess that it can be slow for packages with many functions. Install-time seems relatively straightforward.
- I am not a big fan of having two copies of the functions in the installed package. If the monkey patching is clean, then it is also possible to remove the assertions, and/or we can also put the assertion meta-data somewhere in the installed package.
- `.Rin` files might be in the R source code, this is a common pattern for automake/autoconf, but we cannot use this for R packages, for several reasons. But we don't need to, actually, we just need to be able to run `argufy_package()` as the last thing of the install process.

Maybe we can brainstorm on the syntax a bit, I'll open another comment for that, this one is getting longish.

**Comment by gaborcsardi** [comment]
``` r
#' @param x [character(1)] First argument...
```

So, it seems that we agree that this syntax is not too bad. It would be also nice to be able to 
- have more complex assertions,
- have user-defined assertions and
- have conversions in addition to assertions,
  and keep the syntax simple.

Here are some quick ideas. We can argue that the standard R way of checking arguments is using a conversion instead of an assertion, and then the code above would generate something like this:

``` r
x <- as.character(x)
stopifnot(length(x) == 1, !is.na(x))
```

More complex assertions could be created with something like:

``` r
#' @param x [numeric(1), positive] First argument...
```

which would translate into 

``` r
x <- as.numeric(x)
stopifnot(length(x) == 1, !is.na(x), all(x > 0))
```

The user can define assertions and conversions by providing the corresponding `is.` and/or `as.` functions. E.g.

``` r
as.igraph <- function(x) { ... }
#'  @param graph [igraph] A directed or undirected graph...
```

Conversions vs. assertions are somewhat trickier, if conversions are the default, then maybe assertions can be stated explicitly:

``` r
#' @param x [is.numeric()] A numeric vector...
```

would generate

``` r
stopifnot(is.numeric(x))
```

What do you think?

**Comment by gaborcsardi** [comment]
Do you know a way to ensure that some code or function is run **last** during package installation? (Apart from putting it into a `zzz-` file or last in `Collate`?)

I had a fairly good idea for a workflow with roxygen and patching at install time, but I would need to be able to run code after all R files are loaded, at install time. 

I can put some code into `NAMESPACE`, and that runs before the functions are loaded, and then this code can attach an `on.exit` call to `loadNamespace()`, but `loadNamespace()` clears its exit hooks before it exists, so that does not work. :(

**Comment by gaborcsardi** [comment]
I have come up with some possible workflows. It is possible to make everything relatively easy for the user, but then the implementation will need to get hacky, and requires monkey patching. Maybe it is still not too bad.

This is the workflow as the user sees it:
1. User decides to use argufy, puts `Imports: argufy` in `DESCRIPTION`, and an `argufy::argufy_me()` call into the package.
2. Puts the type declaration in the roxygen comments: 

```
  #' @param x [integer(1)] The number of ...
```
1. Installs the package the usual way, and the assertions are added automatically to the installed functions.

This is not bad, but also not ideal during package development, because to get the assertions, the user needs to install the package. Not sure what we could do about this. Maybe doing something for devtools is possible, and then assertions are added when the user calls `devtools::load_all()`.

The implementation of `argufy_me()` involves parsing the source files (with roxygen or without it) and then tracing `makeLazyLoadDB` to add the assertions before the lazyLoad DB is created. So we do not need to save the assertions anywhere, they are parsed and added at the same time, while the package is installed. It can still be an option for the user to save it into the package, of course, and we can even change the default. With this method, it is easy to save them into the package environment, with some special name, e.g. `.__argufy_assertions__`.

In the future, we can lobby for some install hook, so that the tracing and monkey patching would not be needed.

**Comment by lawremi** [comment]
Have not put a lot of thought into this, but what about just scanning for the function assignments and establishing an active binding for each. When the assignment happens, we decorate the function. In theory, that would work even if someone were to `assignInNamespace()` during development.

**Comment by gmbecker** [comment]
@gaborcsardi I've thought about this in a slightly different context (template S4 class and accessor method generation, mostly) and definitely agree that an install (or arguably build) hook is what we want long term. 

While it's not necessary to keep the assertions around once they've been inserted into the body of the funciton, it seems strange to have extra, meaningful information about the functions and then throw it away again. Why not insert it as attributes on the (modified) functions in a way that would be easy for a JIT compiler to grab. We could do an external table in the package, as you suggest and as is done in methods,  but that seems like a lot of extra look up if we want to use it compared with just having the functions carry their information around.

Another thing @lawremi and I were talking about is that supporting complex assertions is great, but it would be really nice and more useful for static analysis if there were a separate way of declaring types vs custom assertions, rather than all assertions being is.xxx.

Perhaps types could be

```
#' @param x [<integer>]
#' @param y [<integer(1)>]
#' @param z [<myS4class>]
```

and normal assertions would appear outside of the <> as functions or expressions, separated by commas

```
#' @param w [<character>, is.sorted]
#' @param k [<numeric>, all(k>0)]
```

Thoughts?

**Comment by gaborcsardi** [comment]
@gmbecker OK, I guess the functions can contain the assertions, we can just put them in the code, in some way that is inexpensive for the running time. Although hiding it in the code function body be more challenging than one would think. I would not want to use attributes for this.

I don't know, I am not convinced that there is a big difference between user-defined and built-in assertions. Maybe we can define some rules that make it easy for a static analyzer to deduce where an assertion lives, without extra syntax. In general, the easier the syntax is, the better. Special cases make more difficult.

**Comment by gmbecker** [comment]
@gaborcsardi What are your reservations for using attributes? It seems like it's pretty much what they're for. 

As for user defined vs built in assertions, I'm not really thinking in those terms. It's really about type-related assertions vs non-type-related assertions. Those types can be builtins (integer, characater) or user-defined (S4 classes).

 Type information specifically could be really useful in a a lot of ways: making it easier to declare S4 methods, compilation, static error detection. Other assertions are useful for these things too (i.e. length one, allowing to compile down to scalar operations being a big one), but imo they often encode a different type of information. 

As an example, knowing that `crypticfun1(x)` returns TRUE may be useful, but probably not as immediately useful as knowing x is an integer, right?

**Comment by gaborcsardi** [comment]
> What are your reservations for using attributes? It seems like it's pretty much what they're for.

They might interfere with with the user's code. I admit that this is rare, but still. If we are modifying the body anyway, why not just put it there?

>  As an example, knowing that crypticfun1(x) returns TRUE may be useful, but probably not as immediately useful as knowing x is an integer, right?

Right. But an analyzer does not need extra syntax to find out that `is.integer` is a type test for integers.

It may check if the user has defined an `is.integer` function in the package or in an imported package, but ultimately an R static analyzer or jit compiler works with best guesses, anyway.

**Comment by gmbecker** [comment]
> They might interfere with with the user's code. I admit that this is rare, but still. If we are modifying the body anyway, why not just put it there?

I mean, we would get to choose which attributes we put it in, I don't think it would be hard to choose something that was standardized enough that analyzers could always find it but arcane enough that no user code would ever look for it. E.g.  the classic `".__assertion_x__."` or similar. Is your worry that user code will break if a function has ANY attributes on it? that would be a bug in their code, and generally easily fixed, I would think.

> It may check if the user has defined an is.integer function in the package or in an imported package, but ultimately an R static analyzer or jit compiler works with best guesses, anyway.

Yeah, but one of the points here is that if a type is unambiguously declared by the user, it no longer is a best guess. That's actually why we would like the more formal type declaration rather than just a symbol that could (technically) mean anything within an R session...

**Comment by jimhester** [comment]
I think having explicit rd commands for these various different concepts might be more clear than doing heuristics on the name of the functions. i.e. the following would check if the type is integer, if not coerce it to an integer and assert that the length was 1.

``` r
#' @param x \type{integer} \assert{length(x, 1)} \coerce{as.integer}
```

We could have a shorthand for input if needed, and possibly pretty / condense the output as well, but the underlying code would at some point list the different types explicitly and it would be possible for users to be explicit if needed.

The logic for translating these into checks can be as simple as
- If the input is a symbol lookup the function with that symbol and call it with the associated parameter.
- If the input is a call simply evaluate the call.
- checks pass their results to `stopifnot()` or equivalent functions.
- coercions assign their results back to the parameter.

Attributes are already used for function srcrefs which works without issue so I think it would be perfectly appropriate to put the assertions there as well.

**Comment by gaborcsardi** [comment]
@jimhester I like these as well, with some minor reservations:
- In another project of mine I am trying to get rid of Rd markup, in favour of markdown. :)
- AFAIR, if we have new Rd tags, then the package that uses argufy needs to import these, with an `Rdmacros` entry in `DESCRIPTION`, otherwise the there will be an error parsing the help file. So this is again something extra to do for the user. (Although we can also put in the field during install.)
- Now that people can write Rd macros, there is a chance for name clashes there, too.

So I think I would prefer some Rd-less version, mainly because of the markdown. I think it is quite easy to define a small DSL that is also readable in the help file, and we don't need to do heuristics.

**Comment by jimhester** [comment]
:+1: to a simple DSL in markdown instead of Rd tags as long we can make it unambiguous.

**Comment by lawremi** [comment]
I think the idea of using Rd macros. Name/syntax clashes can happen with any approach. By sticking to Rd, the approach generalizes to _all_ R documentation, even that not based on roxygen. One could still define a DSL, but it would just compile down to the Rd macro calls.

**Comment by gaborcsardi** [comment]
@lawremi thats a good point. Ok, I think this is getting quite good.

**Comment by gmbecker** [comment]
@jimhester, @gaborcsardi  I like these ideas as well. Some more thoughts

> ```
> #' @param x \type{integer} \assert{length(x, 1)} \coerce{as.integer}
> ```

It might be more natural if \assert acts like RUnit's `checkEquals` when passed 2 arguments, or `checkTrue` with 1 argument. That would allow the arguments to be actual R symbols (`length(x,1)` is going to be either an error or something very strange) . Also, perhaps  coercion should be type explicit. If a type declaration is, it could take no arguments, e.g.

```
#' @param x \type{integer} \coerce{}
```

resulting in `as(x, "integer")` being invoked in the modified function. It could also imply type when passed one so the \type markup isn't needed, i.e.

```
#' @param x \coerce{integer} \assert{length(x),1}
```

Coercion to non-types (classes) could be called preprocessing, and know that it will be done via a function.

```
#' @param x \type{integer} \preprocess{make_positive}
```

would insert `x = make_positive(x)` into the generated "header" of the modified function. The implicit assumption would be that make_positive leaves `x` unchanged if it meets whatever criteria, and modifies it so that it does met it otherwise.

Thoughts?

**Comment by jimhester** [comment]
Sorry my example was poor I was debating between a couple possibilities and ended up at something I didn't read carefully enough.

I think the assertion should just be a R expression, i.e. `\assert{length(x) == 1}`

The markdown / DSL or what have you compiling down to the Rd eventually is what I had in mind and I agree it would be nice for this work for all R documentation.

**Comment by gaborcsardi** [comment]
@jimhester I agree that it should be just an R expression. And then maybe we can have assertions and coercions:
- `\assert{is.integer(x)}`, and 
- `\coerce{as.integer(x)}`.

I have created a new branch for this: https://github.com/gaborcsardi/argufy/tree/ng

**Comment by gmbecker** [comment]
@gaborcsardi From what we've been talking about, that first one would be a `\type{}` directive, wouldn't it? I thought we had more or less settled on type information being declared differently than general assertions. That is why I was suggesting we differentiate between `\coerce` and `\preprocess` or whatever we decide to call it. 

Also if we are specifying functions that are to be called, it seems like the function symbol is sufficient and easier to read than the actual call. 

You could have different types of assert tags as well, akin RUnit/testthat, if 'ambiguity' in the `\assert` tag is an issue

```
#' @param x \type{integer} \assert{length(x)>0} \assert_equal{length(unique(x)), 5}
```

**Comment by lawremi** [comment]
Seems reasonable to support `\type{class}` as a shortcut for `\assert{is(x, "class")}`. Ideally we would still support a formal notion of type in the metadata, which could be inferred from the `\assert{}` clause, perhaps dynamically through a metadata accessor.

**Comment by gaborcsardi** [comment]
@gmbecker I think we don't need extra `\type{}`s, if you see `\coerce{as.integer(x)}` then you know that it is an integer. Whatever comes out of `as.integer` is an integer, or the function throws an error. I would also avoid having too many tags. Your example can be written as

``` r
#' @param x \coerce{as.integer(x)} \assert{length(x) > 0 && length(unique(x)) == 5}
```

I like the idea of having two tags, because essentially there are two operations we want to perform.

Btw. as for 

> Yeah, but one of the points here is that if a type is unambiguously declared by the user, it no longer is a best guess. That's actually why we would like the more formal type declaration rather than just a symbol that could (technically) mean anything within an R session...

I don't think you can do this in R. IMO you'll never get 100% type safety. E.g. what if you trace or debug the function and change a variable to something else, and then continue running the code?

**Comment by gmbecker** [comment]
@gaborcsardi 

> I don't think you can do this in R. IMO you'll never get 100% type safety. E.g. what if you trace or debug the function and change a variable to something else, and then continue running the code?

I'd say that's akin to poking at specific pieces of memory in C that you know hold variables used by a running program. It's not something we would need to protect against in order to reasonably claim type safety.  Why would we need our system to support "antagonistic" user actions like that? I promise you that I can make R crash  with C code if that is my goal, but that doesn't make R unstable...

**Comment by lawremi** [comment]
Two things:
1. The assert expressions as proposed are redundantly referencing the parameter by name. Perhaps using `.` here would be preferable? A bit harder to read, perhaps, but less redundancy.
2. While I can understand the desire to have two primitive macros, `\assert{}` and `\coerce{}`, type information is often of particular interest, as we know from statically-typed languages. While inference is possible, it is imperfect. Not only does the machine need to infer, but also the reader. `\type{integer}` is clearer, IMO, than `assert{is.integer(x)}`. For one, there is no need to reference the parameter. And then there are annoyances like `is.unsorted(x)`, `is.object(x)`, `is.element(x, y)`, the list goes on and on. Btw, the macro should probably be called `\class{}`.

FYI: related work: https://www.bioconductor.org/packages/release/bioc/vignettes/TypeInfo/inst/doc/TypeInfoNews.pdf

**Comment by gaborcsardi** [comment]
@lawremi 

> 1. The assert expressions as proposed are redundantly referencing the parameter by name. Perhaps using `.` here would be preferable? A bit harder to read, perhaps, but less redundancy.

Yes, I think we can use the dot instead.

> 1. While I can understand the desire to have two primitive macros, `\assert{}` and `\coerce{}`, type information is often of particular interest, as we know from statically-typed languages. While inference is possible, it is imperfect. Not only does the machine need to infer, but also the reader. `\type{integer}` is clearer, IMO, than `assert{is.integer(x)}`. For one, there is no need to reference the parameter. And then there are annoyances like `is.unsorted(x)`, `is.object(x)`, `is.element(x, y)`, the list goes on and on. Btw, the macro should probably be called `\class{}`.

How about just a simple table?
- `as.integer` -> `integer`
- `as.character` -> `character`
- etc.

I understand that for a more complex conversion you can't deduce the type, so we can add types later if needed.

> FYI: related work: https://www.bioconductor.org/packages/release/bioc/vignettes/TypeInfo/inst/doc/TypeInfoNews.pdf

Thanks, I did not know this. The goals are very similar.

**Comment by gmbecker** [comment]
@gaborcsardi 

> I understand that for a more complex conversion you can't deduce the type, so we can add types later if needed.

imo the issue is about who has what info when, and how function authors are likely to be thinking about these types of assertions. The function author has full information about what kind of checks/conversions/etc (s)he wants to declare. No code analysis will achieve that, so why not make it easy for authors to put the useful info into the annotations. We can make sure that get's translated into the functionality they want (and I'm happy to contribute to that effort).

I also think it will be easier/more convenient for function authors to use. Deciding that x is an integer seems much simpler and easier to do than  reasoning that `is.integer` needs to return TRUE because I want x to be an integer. The same goes for coercion ("coerce this to an integer" vs "call as.integer because that will coerce things to an integer"). At that point, we (the authors of argufy, and I'm happy to contribute this part if desired) can write the code that checks that for them (btw for various reasons it's safer to do `is(x, "class")` than `is.class(x)`). The function author's life is easier, and we have a much more semantically rich annotation on the function if it works this way. Let people think at the high level about defensive programming while **argufy** takes care of the details, everyone wins.

> Yes, I think we can use the dot instead.

Once we're using the dot we are no longer in the realm of valid R expressions that can just be evaluated. If we do that, it's not clear what benefit remains for pushing towards complex, hard-to-read compound assertions rather than multiple \assert (or variants) tags in the docs. We could always use a single letter (e.g.,  x) , so that 

```
length(x)>0 && all(x>0) && sum(is.na(x)) == 0
```

is used to generate the (possibly anonymous) function

```
function(x) length(x)>0 && all(x>0) && sum(is.na(x)) == 0
```

To be called on values passed to the argument, though specifying each assertion separately as

```
#' @param arg \assert{length(x)>0, all(x>0), sum(is.na(x))==0}
```

or 

```
#' @param arg \assert{length(x)>0}  \assert{all(x>0)} \assert{sum(is.na(x))==0}
```

Puts less cognitive load on the user. Perhaps others feel differently, though.

**Comment by lawremi** [comment]
If we always use `x`, what happens with inter-argument assertions? If an actual argument is named `x`, there is a conflict. Or are those out of scope? Not exactly clear where to put an inter-argument assertion when specifying assertions at the argument level. Reasoning on types is much simpler than general assertions and still useful.

**Comment by gaborcsardi** [comment]
@lawremi I think the semantics can be simple:
- We replace all single dots with dots with the actual argument.
- We put the expression into the `stopifnot(expr)` assertion template or the `param <- expr` coercion template, and then put it in the body of the function.

(Use the rules @jimhester had above, essentially.)

You can make inter-argument assertions and coercions as well this way.

**Comment by lawremi** [comment]
I realize that. I was just pointing out a minor impedance mismatch, and a particular issue if using `x` instead of `.`.

**Comment by gaborcsardi** [comment]
OK, this is mostly done, although I am sure that it has bugs. I'll write a bunch of test cases soon. 

We can add more features later, e.g. annotated function objects.

Thanks all for the discussion!
