### ISSUE TITLE
Make package a build-time dependency, even if our coercions and assertions are used

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#6]
This seems hard, but we can give it a try. E.g. for `as_enum()` it means that we want to insert the body of `as_enum` into the body of the checked function, not just the `as_enum()` call.

We need a way to decide when to insert the body and when the call. This seems not too hard.

Also, these functions cannot call other functions within the package, or these must be "inlined" as well. This seems hard.

**Comment by jimhester** [comment]
This seems to work

``` r
inline_functions <- function(x, nms) {
  recurse <- function(y) {
    lapply(y, inline_functions, nms = nms)
  }

  if (is.atomic(x) || is.name(x)) {
    x
  } else if (is.call(x)) {
    if (as.character(x[[1]]) %in% nms) {
      x[[1]] <- inline_functions(match.fun(x[[1]]), nms)
    }
    as.call(recurse(x))
  } else if (is.function(x)) {
    formals(x) <- inline_functions(formals(x), nms = nms)
    body(x) <- inline_functions(body(x), nms = nms)
    x
  } else if (is.pairlist(x)) {
    # Formal argument lists (when creating functions)
    as.pairlist(recurse(x))
  } else if (is.expression(x)) {
    # shouldn't occur inside tree, but might be useful top-level
    as.expression(recurse(x))
  } else if (is.list(x)) {
    # shouldn't occur inside tree, but might be useful top-level
    recurse(x)
  } else {
    stop("Unknown language class: ", paste(class(x), collapse = "/"),
      call. = FALSE)
  }
}

f1 <- function(x) { as_enum(x) }
inline_functions(f1, ls(asNamespace("argufy")))
# function (x)
# {
#     (function (arg)
#     {
#         formal.args <- formals(sys.function(sys.parent()))
#         choices <- eval(formal.args[[deparse(substitute(arg))]])
#         match.arg(arg, choices = choices)
#     })(x)
# }
```

Perhaps a few of the cases are unneeded for this use case, code was adapted from `pryr::modify_lang()`.

**Comment by gaborcsardi** [comment]
Wow! Thanks. Btw. I can add you as a collab if you don't mind. :)

**Comment by jimhester** [comment]
Fine with me!

**Comment by gaborcsardi** [comment]
Cool. We can still discuss bigger changes. :)

**Comment by jimhester** [comment]
I will probably still do mostly pull requests anyway, don't want to ruin your baby :smile:

**Comment by gaborcsardi** [comment]
So, to be honest, this code is a bit scary to me. :) Maybe we can do sg simpler initially, e.g. just label our own assertions, recognize them and inline them. Make sure that we do not call other functions from the package, we can check this from the tests I guess. 

Most assertions will be very simple I imagine. 

I am afraid that things like `if (as.character(x[[1]]) %in% nms)` are just not robust enough. Obviously, we can improve them, but still.

**Comment by jimhester** [comment]
The function as written had a small bug with nested calls, explictly checking if `x[[1]]` is a symbol remedies this.

``` r
inline_functions <- function(x, nms) {
  recurse <- function(y) {
    lapply(y, inline_functions, nms = nms)
  }

  if (is.atomic(x) || is.name(x)) {
    x
  } else if (is.call(x)) {
    name <- x[[1]]
    if (is.symbol(name) && as.character(name) %in% nms) {
      x[[1]] <- inline_functions(match.fun(name), nms = nms)
    }
    as.call(recurse(x))
  } else if (is.function(x)) {
    formals(x) <- inline_functions(formals(x), nms = nms)
    body(x) <- inline_functions(body(x), nms = nms)
    x
  } else if (is.pairlist(x)) {
    # Formal argument lists (when creating functions)
    as.pairlist(recurse(x))
  } else if (is.expression(x)) {
    # shouldn't occur inside tree, but might be useful top-level
    as.expression(recurse(x))
  } else if (is.list(x)) {
    # shouldn't occur inside tree, but might be useful top-level
    stop()
    recurse(x)
  } else {
    stop("Unknown language class: ", paste(class(x), collapse = "/"),
      call. = FALSE)
  }
}
```

Symbols will always be coercible to character.

`x %in% nms` will always return `TRUE` or `FALSE` for any type, except when `x == NULL`

``` r
'a' %in% 1:10
# FALSE
1 %in% 1:10
# TRUE
NA %in% 1:10
# FALSE
NULL %in% 1:10
# logical(0)
```

The last case can be fixed by wrapping with `isTRUE()`

``` r
isTRUE(NULL %in% 1:10)
# FALSE
```

However it will never happen in practice because symbols cannot be `NULL`.

Symbols cannot be more than length 1, so we don't have to worry about the vectorization of `%in%`.

Using `match.fun()` was done for example, in practice using `get(mode = "function", inherits = FALSE, envir = asNamespace(argufy))` would be safer and could be done upstream of this function (then using the `names(nms)` to match in `inline_functions`).

Also we could restrict the functions in `nms` to be only those assertions which we know need to be inlined, and this code only needs to run on the expressions to the right of `?`, which reduces the problem space.  We could also allow inlining to user configurable, as it has limited benefits if you are not concerned with having argufy as only a build time dependency.

If you are concerned with the rest of the recursion being accurate as I said this function was derived from [hadley/pryr/R/modify-lang.r#L21-L49](https://github.com/hadley/pryr/blob/87bec0fede7da6f42a0c65b424f3ba33743fb8fd/R/modify-lang.r#L21-L49).  Hadley walks through the cases of a similar function in [Walking the AST with recursive functions](http://adv-r.had.co.nz/Expressions.html#ast-funs).

As a practical proof a function with the same basis is the workhorse in [covr](https:://github.com/jimhester/covr) which adds counting logic to each call ([jimhester/covr/R/trace_calls.R#L10-L78](https://github.com/jimhester/covr/blob/2c55c2ea5c207fbd735cb25bf21b0f2ddf977a47/R/trace_calls.R#L10-L78)).  Covr works successfully with [~450 packages on GitHub](https://github.com/search?q=filename%3A.yml+jimhester+covr&ref=searchresults&type=Code&utf8=%E2%9C%93) and [~300 on Bioconductor](https://codecov.io/github/Bioconductor-mirror/) so I am confident the recursion is correct for walking R's AST.

If you are still not comfortable with the code I respect your decision and you are welcome to use an alternative approach.

**Comment by gaborcsardi** [comment]
I am just playing the devil's advocate here. :)

> Symbols will always be coercible to character.
> x %in% nms will always return TRUE or FALSE for any type, except when x == NULL

Yeah, but what if the symbol is defined in another package as well, and the user meant to call that?

> We could also allow inlining to user configurable, as it has limited benefits if you are not concerned with having argufy as only a build time dependency.

I would not do this initially, don't want to commit to it just yet.

> As a practical proof a function with the same basis is the workhorse in covr which adds counting logic to each call (jimhester/covr/R/trace_calls.R#L10-L78). Covr works successfully with ~450 packages on GitHub and ~300 on Bioconductor so I am confident the recursion is correct for walking R's AST.

Yes, this is good, but not really a proof. In many cases, if you miss the right function, your coverage count will be a bit wrong. Or maybe not even that. You would never notice this.

> If you are still not comfortable with the code I respect your decision and you are welcome to use an alternative approach.

It seemed like a good idea in general, but walking the whole AST seems over-engineering to me, even it technically this is the best solution.

What I suggest we do is putting a class, say `argufy_inline` on the assertions (and coercions?) that we define in `argufy`, and also check for the presence of this class, at the top level. Then I am more comfortable with inlining functions with this class.

**Comment by jimhester** [comment]
> Yeah, but what if the symbol is defined in another package as well, and the user meant to call that?

This situation is tricky I guess, I am not sure how to have package code use the users' search path...

Like I said I am fine going another direction and checking for the `argufy_inline` class seems reasonable to me, carry on!

**Comment by gaborcsardi** [comment]
I would still do your AST walk, maybe a bit modified: 1) only start inlining if the `argufy_inline` class is present, and 2) stop inlining if nothing in inlined at a level.

 Although this just complicates your nice and tested function....

**Comment by gaborcsardi** [comment]
With the new approach this is not possible, because we need the install process to load argufy before the package being installed, and that means that it must be in `Imports` or in `Depends`. So closing this now.
